### ISSUE TITLE
Speak the Answers

### ISSUE THREAD

**Issue by mmcgreg** [mmcgreg/components-on-a-grid#1]
[mcgregor-morgan-030-speak-the-answers.m4a.zip](https://github.com/mmcgreg/components-on-a-grid/files/7232904/mcgregor-morgan-030-speak-the-answers.m4a.zip)

Thanks, @thatkidmadrid !

**Comment by thatkidmadrid** [comment]
Hey Morgan,
I notice that you didn't have the grid on the body even though you started to by setting `grid-template-areas`; and I also notice that you set up two grids. This would have made some other spacings more tricky, but you got it to match the reference so you'll get the full marks 🎉

Remember that we covered in our activity in class that the layout was a 2x2 grid, so we expect to see that reflected in the css (and i think you probably started on the right track by setting the `grid-template-areas` in the `body`. This would also explain why `grid-area` may not have been working for you and why I see both `grid-area` and `grid-column/grid-row` being used at the same time

Anyways, the recording sounds great! Very clear, and well communicated 👍

**Comment by mmcgreg** [comment]
@thatkidmadrid 
It all makes sense now! I totally blanked on continuing the 2x2 grid while coding it but that explains the tinkering I had to do to get it to match the reference. I was super proud when I managed to get it within 2%! Thanks for pointing it out, that's really helpful!
